### ISSUE TITLE
accountFavoriteTV + accountRatedTV

### ISSUE THREAD

**Issue by LekoArts** [grantholle/moviedb-promise#14]
Hi!

Thank you for creating this library, it works superb. However I'm missing some endpoints:
https://developers.themoviedb.org/3/account/get-favorite-tv-shows
https://developers.themoviedb.org/3/account/get-rated-tv-shows

Could you please add these?

Thanks!

**Comment by grantholle** [comment]
You should be good with `1.3.2`! Thanks for letting me know

**Comment by LekoArts** [comment]
Thank you very much for the quick response :)
