### ISSUE TITLE
Gatsby Plugin ❤

### ISSUE THREAD

**Issue by LekoArts** [grantholle/moviedb-promise#15]
Hey,

thank you for your package 👍 Just wanted to let you know that I built a Gatsby source plugin with it (if you're interested in seeing what other people build with your stuff):

https://github.com/LekoArts/gatsby-source-tmdb

Have a nice day! 😊

**Comment by grantholle** [comment]
Sweet! Great work and collaboration! 💯

Thanks for letting me know
