### ISSUE TITLE
API token is requested multiple times when sending multiple queries in a quick succession

### ISSUE THREAD

**Issue by Zentryn** [grantholle/moviedb-promise#16]
When sending multiple queries in a quick succession, the module requests the MovieDB API token multiple times, even though it should only request it once. This leads to wasted API calls and it fills up the rate limit. Here's a simple example:
```
const moviedb = new MovieDB(API_KEY);

for (var i = 0; i < 20; i++) {
    moviedb.searchMovie({ query: "Movie Name" })
        .then(data => {
            console.log(data);
        })
        .catch(err => {
            console.error(err);
        });
}
```
In this case the module requests a new API token for each of the requests. This leads to a total of **40** requests, instead of 21. This could be fixed by checking if a token is already being requested, and waiting for that request to resolve.

**Comment by rontav** [comment]
Good job catching this!
