### ISSUE TITLE
Test "should only request one token" fails

### ISSUE THREAD

**Issue by rontav** [grantholle/moviedb-promise#20]
https://github.com/grantholle/moviedb-promise/blob/dbc442a4f1147bffd1251023c4453ee2a9491c1c/index.js#L44-L47

The `await` was purposely removed so that `requestToken` will return immediately and the user will await on the same variable if multiple calls were made before the first response was received.

Since the user it's already expecting a promise (extract from README.md):
```
// Creating a session id would look something like this
moviedb.requestToken().then(token => {
  // Now you need to visit this url to authorize
  const tokenUrl = `https://www.themoviedb.org/authenticate/${token}`
}).catch(console.error)
```
we can return the makeRequest promise directly.

"should only request one token" test should have caught this but it doesn't seem to fail everytime with the broken version. I think it depends on the speed of the first request and can't find a way to correctly test this (first world problems? :sweat_smile:).

**Comment by grantholle** [comment]
Interesting, yeah all my tests pass every time. Nice catch
