### ISSUE TITLE
Rate limiting has been removed from TMDb

### ISSUE THREAD

**Issue by Zentryn** [grantholle/moviedb-promise#23]
On December 16th 2019, TMDb removed rate limiting from their API. The rate limiting in this library should thus not be needed anymore. See [updated docs](https://developers.themoviedb.org/3/getting-started/request-rate-limiting) and [forum discussion](https://www.themoviedb.org/talk/5df7d28326dac100145530f2).

**Comment by grantholle** [comment]
I've made using the rate limiter off by default (it was on previously). This way the functionality can still exist if you want it to, for whatever the reason.

If you use the default second and third parameters when initializing the object, it won't use rate limits with `1.5`.

Thanks for bringing this to my attention
