### ISSUE TITLE
movieDb is not a constructor

### ISSUE THREAD

**Issue by iamphoenix310** [grantholle/moviedb-promise#35]
After setting up the file and importing the package. When I run the script it gives the following error. 

TypeError: movieDb is not a constructor

Here's my code: 

```
const {movieDb} = require('moviedb-promise')
const moviedb = new movieDb('my-key')

const findMovie = async title => {
    // Equivalant to { query: title }
    const res = await moviedb.searchMovie(title)
   
    return res
  }
   
  try {
    const results = findMovie('alien')
    console.log(results)
  } catch (e) {
    console.log(e)
  }
```

**Comment by grantholle** [comment]
I _think_ it's because capitalization matters when importing the package. Try this:

```js
const { MovieDb } = require('moviedb-promise')
```

Replace `movieDb` with `MovieDB`.

**Comment by iamphoenix310** [comment]
I tried that too but getting same error. 

> Replace `movieDb` with `MovieDB`.

**Comment by grantholle** [comment]
What happens when you clone and run this [sample project](https://github.com/grantholle/moviedb-promise-playground)?

**Comment by iamphoenix310** [comment]
> What happens when you clone and run this [sample project](https://github.com/grantholle/moviedb-promise-playground)?
It runs perfectly when I run this sample project.

**Comment by grantholle** [comment]
🤔 

What's the output when you run `npm view moviedb-promise version` in your project? Could you paste the full snippet again?

**Comment by iamphoenix310** [comment]
3.1.2

**Comment by grantholle** [comment]
What about this?

```js
const { MovieDb } = require('moviedb-promise')
const moviedb = new MovieDb('my-key')
```

**Comment by iamphoenix310** [comment]
This is what I was trying at first. it's giving an error.  

```
const moviedb = new movieDb('my-key')
                ^
TypeError: movieDb is not a constructor
```

**Comment by grantholle** [comment]
Ok, yeah I think the problem is making sure you're requiring it like `{ MovieDb }` and then doing `new MovieDb()`.

```js
```

**Comment by iamphoenix310** [comment]
This is working now. It's returning Promise  { <pending> }
Thanks
> 
> ```js
> const { MovieDb } = require('moviedb-promise')
> const moviedb = new MovieDb('my-key')
> ```

The solution is we have to make `M` capital in the `MovieDb`

**Comment by grantholle** [comment]
Ok great!
