### ISSUE TITLE
[Help Wanted] Fetching Multiple person name and images

### ISSUE THREAD

**Issue by iamphoenix310** [grantholle/moviedb-promise#36]
Hi, There's no issue. I am just a beginner developer and couldn't understand how to fulfill my requirement. Please help. I want to fetch multiple celebrities and store only their name and images into my database. 

How can I fetch multiple celeb pics, their names, and gender without making the requests too much complicated? Here's the initial request that I made. But If I want to fetch 150,000 celebs that'll be a nightmare. Please provide any code example. that'll make it easier for me to fetch celebs. 

```
const personPic = async () => {
  const person1 = await moviedb.personInfo('78080')
  const config = await moviedb.configuration()
  console.log(`${person1.name}`)
  console.log(
    `${config.images.secure_base_url}${config.images.profile_sizes[2]}${person1.profile_path}`
  )
}

personPic()

```

**Comment by grantholle** [comment]
You're definitely on the right track. Ultimately I don't think there's any way to get around doing a request for each celeb, but you can move the configuration call to a different function initially, that way you're only calling it once.

```js
moviedb.configuration().then(async config => {
  const base = config.images.secure_base_url
  const size = config.images.profile_sizes[2]

  // Somehow crawl celebs...
  // ...
  const person = await await moviedb.personInfo('78080')
  console.log(person.name)
  console.log(base + size + person.profile_path)
})
```

I'm not sure the best way to crawl for celebs. You may start at a show/movie and get the credits. The credits return an array of people details, including the `profile_path` attribute. That would save the work of calling `personInfo` on each person.

Does that help at all?

**Comment by iamphoenix310** [comment]
Yeah, it helps a lot. Thank you so much.
