### ISSUE TITLE
Some request URLs are wrong (extra slash prefix)

### ISSUE THREAD

**Issue by Aaronaught** [grantholle/moviedb-promise#37]
I was trying to call `movieExternalIds` and getting 404s - eventually managed to figure out what URL it was actually sending, and it looks like `https://api.themoviedb.org/3//movie/123/external_ids`. Note the extra slash after `3//`, which is caused by a leading slash in the string used by `movieExternalIds`.

It looks like one other method also has this, `episodeChanges`. Both should have the leading slash removed so they work correctly.

For now I can work around the issue by manually specifying the `url` in the Axios options, though it's kind of silly to be doing with an API client library.

**Comment by grantholle** [comment]
Fixed in `moviedb-promise@3.1.3`, thanks for discovering this
