### ISSUE TITLE
Watch Providers endpoint is missing

### ISSUE THREAD

**Issue by david-808** [grantholle/moviedb-promise#39]
https://developers.themoviedb.org/3/movies/get-movie-watch-providers

Looks like this endpoint is not available in this package, would be nice to have it.

**Comment by david-808** [comment]
https://developers.themoviedb.org/3/tv/get-tv-watch-providers

The TV version is missing too.

**Comment by grantholle** [comment]
Added in `moviedb-promise@3.1.4`, thanks for spotting those! They add new endpoints from time to time.

`movieWatchProviders` and `tvWatchProviders` are available
