### ISSUE TITLE
Possible issue in the documentation : Submitted a pull request 

### ISSUE THREAD

**Issue by pankaja92** [grantholle/moviedb-promise#5]
In **Installation** part of the documentation it mention to install the module by `npm install moviedb-promise --save`
But in **Usage** it mention to use `moviedb` module instead of `moviedb-promise`

```
const MovieDb = require('moviedb')
const moviedb = new MovieDb('your api key')
```

So Isn't the usage should be 

```
const MovieDb = require('moviedb-promise')
const moviedb = new MovieDb('your api key')

```
instead.

**Comment by grantholle** [comment]
Fixed by PR #4
