### ISSUE TITLE
types probably incorrect

### ISSUE THREAD

**Issue by LeoLfL** [grantholle/moviedb-promise#57]
[docs popular tv-shows](https://developers.themoviedb.org/3/tv/get-popular-tv-shows)
[docs top-rated tv shows](https://developers.themoviedb.org/3/tv/get-top-rated-tv)
[docs tv-on-the-air](https://developers.themoviedb.org/3/tv/get-tv-on-the-air)

moviedb-promise wants an id passed, but I see no reason why and in the docs of tmdb the id parameter for popular-tv-shows is not given either

the same for tv top-rated and tv-on-the-air and maybe  some another 

Also looks like TvResult and MovieResult shouldn't have media_type property

**Comment by grantholle** [comment]
Ok thanks for the heads up, I'll check it out

**Comment by grantholle** [comment]
Found the problem and fixed in `3.1.15`. Thanks again for letting me know

**Comment by LeoLfL** [comment]
> Found the problem and fixed in `3.1.15`. Thanks again for letting me know

welcome
