### ISSUE TITLE
Cannot read property 'makeRequest' of undefined

### ISSUE THREAD

**Issue by Bemmm** [grantholle/moviedb-promise#58]
gettings an error "Cannot read property 'makeRequest' of undefined" when calling "movieInfo"

const { MovieDb } = require('moviedb-promise');
const moviedb = new MovieDb(process.env.MOVIEDB_API_KEY);

let a = moviedb.movieInfo({ id: req.params.entityId });

**Comment by grantholle** [comment]
Hey @Bemmm, would you mind creating a super simple repo that can replicate this problem? In my own testing I'm able to call `movieInfo` successfully.

From that snippet, it looks like you're correctly setting it up.
