### ISSUE TITLE
.tvInfo Problem 

### ISSUE THREAD

**Issue by canskld** [grantholle/moviedb-promise#59]
Hi I'm trying to pull data with tvInfo 
I'm success with pulling data but I can't specify a language parameter 
pls Help 
Here is my code;
`moviedb
.tvInfo('66732')
        .then((resInfo) => {
            console.log(resInfo)
        })`

**Comment by grantholle** [comment]
Hey @canskld, you'll need to use an object instead of passing the ID:

```js
moviedb.tvInfo({ id: 66732, language: 'fr' }).then(console.log)
```
