### ISSUE TITLE
Tnterface Translation is diffent from API Reference

### ISSUE THREAD

**Issue by CyberRim** [grantholle/moviedb-promise#71]
package:"moviedb-promise": "^3.4.0"
``` typescript
//node_modules/moviedb-promise/dist/request-types.d.ts
export interface Translation {
    iso_3166_1?: string;
    iso_639_1?: string;
    name?: string;
    english_name?: string;
    data?: {
        title?: string;
        overview?: string;
        homepage?: string;
    };
}
```
It should be `translation.data.name` rather than `translation.data.title`

![image](https://github.com/grantholle/moviedb-promise/assets/22914071/df5ba679-e8bd-4663-8517-994245976be6)

![image](https://github.com/grantholle/moviedb-promise/assets/22914071/7bfeb575-18a1-4b5f-bb3c-254f4c6402d7)

**Comment by grantholle** [comment]
Thanks for noticing. `3.4.1` has the updated type
